
export const SORT_PRODUCTS="SORT_PRODUCTS"
export const FILTER_PRODUCTS="FILTER_PRODUCTS"
export const GET_PRODUCTS_LOADING="GET_PRODUCTS_LOADING"
export const GET_PRODUCTS_ERROR="GET_PRODUCTS_ERROR"
export const GET_PRODUCTS_SUCCESS=" GET_PRODUCTS_SUCCESS"